version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
      # Usar a segunda migration para criar o banco na inicialização
      - ./migrations/002_create_schema.sql:/docker-entrypoint-initdb.d/002_create_schema.sql:ro
    ports:
      - "${PGPORT:-5432}:5432"

  
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGHOST: db
      MQTT_URL: mqtt://mqtt:1883
      MQTT_TOPIC: env/master/+/+
      PORT: ${PORT:-3000}
    depends_on:
      - db
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./:/usr/src/app:ro

volumes:
  db_data:
  mosquitto_data:
  mosquitto_log:
